# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Business-OnlinePayment-Beanstream
version:      0.02
version_from: 
installdirs:  site
requires:
    Business::OnlinePayment:       0
    URI::Escape:                   0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
